### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by SnipahKitteh** [SnipahKitteh/Holonomic-Experimentation#1]
- [x] Set up a basic skeleton
- [x] Implement basic directional control (timed)
- [ ] Implement standard user control
- [x] Implement timed turning functions
- [ ] Implement functions that combine directional control with timed control
- [ ] Implement polar turning control
- [ ] Implement radial turning control
- [ ] Implement PID control for all functions (optional)
- [ ] Implement function to perfectly control polar directions(optional)
